const lang = {
    en: {
        inCategory: 'In Category',
        title: 'iStoriez',
        subtitle: 'Stories for Children',
        sendFeedback: "Send Feedback",
        no: 'No',
        reads: "reads",
        votes: "ratings",
        whatDidYouThink: "What did you think",
        forKids: "for Children",
        kids: "Children",
        about: "about",
        audioStories: "Audio Stories",
        allAudioStories: "All Audio Stories",
        for: "for",
        settings: "Settings",
        thisWeek: "This week",
        daysAgo: "days ago",
        weekAgo: "week ago",
        weeksAgo: "weeks ago",
        monthAgo: "month ago",
        monthsAgo: "months ago",
        yearAgo: "year ago",
        today: "Today",
        yesterday: "Yesterday",
        all: "All",
        years: "Years",
        by: "by",
        favorites: "Favorites",
        recentlyRead: "Your Latest Reads",
        eStory: "E-Story",
        soundStory: "Audio Story",
        yourLibrary: "Your Library",
        author: "Author",
        authors: "Authors",
        mostReadStories: "Most Read Last Month",
        newStories: "Latest Bedtime Stories",
        shortStories: "Short Bedtime Stories",
        mediumStories: "Medium-length Bedtime Stories",
        longStories: "Long Bedtime Stories",
        story: "Story",
        stories: "Bedtime Stories",
        category: "Category",
        categories: "Categories",
        lengths: "Lengths",
        whatDoYouThink: "What do you think?",
        nameOptional: "Name (optional)",
        emailOptional: "E-mail (optional)",
        message: "Message",
        send: "Send",
        removeFromFavorites: "Remove from Favorites",
        removedFromFavorites: "Removed from Favorites",
        addToFavorites: "Add to Favorites",
        addedToFavorites: "Added to Favorites",
        yourFavorites: "Your Favorites",
        noFavorites: "No favorites added yet. Mark a story as favorite and it will show here.",
        privacyPolicy: "Privacy Policy",
        copyright: "Copyright",
        languages: "Languages",
        selectLanguage: "Select Language",
        share: "Share...",
        swedish: "Swedish",
        english: "English",
        theEnd: "The end",
        storiesBy: "Bedtime Stories by",
        fourOfour: "The page you tried to reach does not exist.",
        moreCategories: "More categories",
        htmlLang: "en",
        indexTitle: "iStoriez - Bedtime Stories Online",
        indexDescription: "Read and listen to bedtime stories for children online for free. Filter by age, length and category.",
        moreBy: "More by",
        moreFrom: "More from",
        menu: "Menu",
        sendFeedback: "Send Feedback",
        istoriezOnFacebook: "iStoriez on Facebook",
        noReads: "No stories read yet. Stories you read will show here.",
        darkTheme: "Dark Mode",
        uppercase: "Uppercase",
        allAuthors: "All Authors",
        aboutIstoriez: "About iStoriez",
        narrators: "Narrators",
        narrator: "Narrator",
        narrated: "Narrated",
        moreNarratedBy: "More narrated by",
        speechSynthesis: "Speech Synthesis",
        allCategories: "All Categories",
        allNarrators: "All Narrators",
        yearsShort: "age",
        read: "Read",
        aboutTheAuthor: "About the Author",
        excerpt: "Excerpt",
        listenNow: "Listen",
        yourGrade: "Your rating",
        aboutThisStory: "About This Story",
        mail: "Mail",
        search: "Search",
        searchInIstoriez: "Search for a bedtime story",
        rateTheStory: "Rate This Story",
        commentTheStory: "Comment This Story",
        free: "Free",
        allBedtimeStories: "All Bedtime Stories",
        bedtimeStory: "Bedtime Story",
        allAges: "All Ages",
        donate: "Donate",
        blog: "Blog",
        with: "With",
        views: "views",
        online: "Online"
    },
    se: {
        inCategory: "i kategorin",
        title: 'iStoriez',
        subtitle: 'Godnattsagor på nätet',
        sendFeedback: "Skicka feedback",
        no: "Inga",
        reads: "läsningar",
        votes: "betyg",
        whatDidYouThink: "Vad tyckte du",
        forKids: "för barn",
        kids: "barn",
        about: "om",
        audioStories: "Ljudsagor",
        allAudioStories: "Alla ljudsagor",
        for: "för",
        settings: "Inställningar",
        thisWeek: "Den här veckan",
        daysAgo: "dagar sedan",
        weekAgo: "vecka sedan",
        weeksAgo: "veckor sedan",
        monthAgo: "månad sedan",
        monthsAgo: "månader sedan",
        yearAgo: "år sedan",
        today: "Idag",
        yesterday: "Igår",
        all: "Alla",
        years: 'år',
        by: "av",
        eStory: "E-saga",
        soundStory: "Ljudsaga",
        favorites: "Favoriter",
        recentlyRead: "Dina senast lästa sagor",
        yourLibrary: "Ditt bibliotek",
        author: "Författare",
        authors: "Författare",
        mostReadStories: "Mest lästa förra månaden",
        newStories: "Senaste godnattsagorna",
        shortStories: "Korta godnattsagor",
        mediumStories: "Mellanlånga godnattsagor",
        longStories: "Långa godnattsagor",
        story: "Saga",
        stories: "Godnattsagor",
        category: "Kategori",
        categories: "Kategorier",
        lengths: "Längder",
        whatDoYouThink: "Vad tycker du?",
        nameOptional: "Namn (valfritt)",
        emailOptional: "E-post (valfritt)",
        message: "Meddelande",
        send: "Skicka",
        with: "med",
        removeFromFavorites: "Ta bort från favoriter",
        removedFromFavorites: "Borttagen från favoriter",
        addToFavorites: "Lägg till i favoriter",
        addedToFavorites: "Tillagd i favoriter",
        yourFavorites: "Dina favoriter",
        noFavorites: "Inga favoriter tillagda. Favoritmarkera en godnattsaga så visas den här.",
        privacyPolicy: "Integritetspolicy",
        copyright: "Copyright",
        languages: "Språk",
        selectLanguage: "Välj språk",
        share: "Dela...",
        swedish: "Svenska",
        english: "Engelska",
        theEnd: "Slut",
        storiesBy: "Sagor av",
        fourOfour: "Sidan du försökte nå finns inte.",
        moreCategories: "Fler kategorier",
        htmlLang: "sv",
        indexTitle: "iStoriez - Godnattsagor på nätet",
        indexDescription: "Klassiska godnattsagor gratis på nätet. Läs och lyssna. Filtrera på ålder, längd och kategori.",
        moreBy: "Mer av",
        moreFrom: "Mer ur",
        menu: "Meny",
        sendFeedback: "Skicka feedback",
        istoriezOnFacebook: "iStoriez på Facebook",
        noReads: "Inga lästa sagor ännu. Godnattsagor du läst visas här.",
        darkTheme: "Mörkt läge",
        uppercase: "Versaler",
        allAuthors: "Alla författare",
        aboutIstoriez: "Om iStoriez",
        narrators: "Berättare",
        narrator: "Berättare",
        narrated: "berättade",
        moreNarratedBy: "Mer berättat av",
        speechSynthesis: "Talsyntes",
        allCategories: "Alla kategorier",
        allNarrators: "Alla berättare",
        yearsShort: "år",
        read: "Läs",
        aboutTheAuthor: "Om författaren",
        excerpt: "Utdrag",
        listenNow: "Lyssna",
        yourGrade: "Ditt betyg",
        aboutThisStory: "Om den här sagan",
        mail: "E-post",
        search: "Sök",
        searchInIstoriez: "Sök efter godnattsaga",
        rateTheStory: "Betygsätt sagan",
        commentTheStory: "Kommentera sagan",
        free: "Gratis",
        allBedtimeStories: "Alla godnattsagor",
        bedtimeStory: "Godnattsaga",
        allAges: "Alla åldrar",
        donate: "Donera",
        blog: "Blogg",
        views: "läsningar",
        online: "på nätet"
    }
}

const slug = {
    en: {
        all: '/all/',
        menu: "/menu/",
        audioStories: "/audio-stories/",
        settings: "/settings/",
        authors: "/authors/",
        ages: "/ages/",
        categories: "/categories/",
        thankYou: "/thank-you/",
        feedback: "/feedback/",
        privacyPolicy: "/privacy-policy/",
        copyright: "/copyright/",
        languages: "/languages/",
        shareMailTo: "mailto:?subject=Tip%20about%20story&body=Read%20the%20story%20here:%20",
        shortStories: "/short-stories/",
        mediumStories: "/medium-stories/",
        longStories: "/long-stories/",
        yourLibrary: "/your-library/",
        yourFavorites: "/your-library/favorites/",
        facebook: "https://www.facebook.com/iStoriez",
        github: "https://github.com/magnusarinell/istoriez.com",
        mostReadStories: "/most-read-last-month/",
        newStories: "/latest-stories/",
        about: "/about-istoriez/",
        narrators: "/narrators/",
        search: "/search/",
        donate: "/donate/",
        blog: "/blog/"
    },
    se: {
        all: '/alla/',
        menu: "/meny/",
        audioStories: "/ljudsagor/",
        settings: "/installningar/",
        authors: "/forfattare/",
        ages: "/aldrar/",
        categories: "/kategorier/",
        thankYou: "/tack/",
        feedback: "/feedback/",
        privacyPolicy: "/integritetspolicy/",
        copyright: "/copyright/",
        languages: "/sprak/",
        shareMailTo: "mailto:?subject=Tips%20om%20saga&body=Jag%20vill%20tipsa%20om%20en%20saga.%20Läs%20hela%20sagan%20här:%20",
        shortStories: "/korta-sagor/",
        mediumStories: "/mellanlanga-sagor/",
        longStories: "/langa-sagor/",
        yourLibrary: "/ditt-bibliotek/",
        yourFavorites: "/ditt-bibliotek/favoriter/",
        facebook: "https://www.facebook.com/iStoriezSverige",
        github: "https://github.com/magnusarinell/istoriez.com",
        mostReadStories: "/mest-lasta-forra-manaden/",
        newStories: "/senaste-sagorna/",
        about: "/om-istoriez/",
        narrators: "/berattare/",
        search: "/sok/",
        donate: "/donera/",
        blog: "/blogg/"
    }
}

const eng = process.env.GATSBY_SITE_LANG === "en";

const strings = eng ? lang.en : lang.se;
const slugs = eng ? slug.en : slug.se;

module.exports = { strings, slugs };