name: Trigger Netlify Build
on:
  schedule:
    - cron: '00 14 * * 5'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request for main
        env:
          MAIN: ${{ secrets.MAIN }}
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/$MAIN
      - name: Curl request for pwa
        env:
          PWA: ${{ secrets.PWA }}
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/$PWA