name: Trigger Netlify Build
on:
  schedule:
    - cron: '00 14 * * 5'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        env:
          BUILD_HOOK: ${{ secrets.BUILD_HOOK }}
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/$BUILD_HOOK